name: Deploy Apps Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Write clasp auth config
        run: echo '${{ secrets.CLASPRC_JSON }}' > ~/.clasprc.json

      - name: Write clasp project config
        run: echo '${{ secrets.CLASP_JSON }}' > .clasp.json

      - name: Push to Apps Script
        run: npm run push

      - name: Run Apps Script function
        run: npx clasp run runPlanner

      # this project doesn't need a deployment
      